//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazki
    {
        public int Id_ksiazki { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public string Bestseller { get; set; }
    }
}
