//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        public int Id_Wypozyczenia { get; set; }
        public Nullable<int> ID_Pracownika { get; set; }
        public Nullable<int> ID_Klienta { get; set; }
        public Nullable<int> ID_Ksiazki { get; set; }
    }
}
